application: facebook-rnn
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /.well-known/acme-challenge
  static_dir: acme-challenge
- url: /static
  static_dir: static
  secure: always
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: main.app
  secure: always